version: '3'
services: 
    nginx:
        image: nginx:latest
        ports: 
            - 8080:80
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./www/html:/var/www/html
        depends_on: 
            - php
    
    php:
        build: ./php
        volumes:
            - ./www/html:/var/www/html
        depends_on: 
            - db

    db:
        build: ./mysql
        restart: always
        ports: 
            - 13306:3306
        volumes: 
            - ./mysql/data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: testdb
            MYSQL_ROOT_PASSWORD: passward
            TZ: Asia/Tokyo