CREATE TABLE test_comments (
    id INT NOT NULL,
    name VARCHAR(20)  NOT NULL,
    text VARCHAR(140) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
);